import Head from 'next/head'
import Image from 'next/image'
import Todolist from '@/components/Todolist';
import React, { useState, useEffect } from 'react'
const listallitems = 'https://yxyoxpxrbi.execute-api.us-east-1.amazonaws.com/dev/todos';
const createitem = 'https://yxyoxpxrbi.execute-api.us-east-1.amazonaws.com/dev/todos';

export async function getServerSideProps() {
  const res = await fetch(listallitems);
  const data = await res.json();
  return {
    props: {
      data
    }
  }
}

export default function Home({data}) {
  data  = data['Items']
  const [newTask, setNewTask] = useState({});

  const handleChange = (event) => {
    setNewTask({ ...newTask, 'text': event.target.value });
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
      const response = await fetch(listallitems, {
        method: "POST",
        headers: {
          // 'Access-Control-Allow-Origin': '*',
          // 'Access-Control-Allow-Credentials': true,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(newTask),
      })
      .then(response => response.json())
      .then(data => {
        console.log('Success:', data);
      })
      .catch(error => {
        console.error('Error:', error);
      });
    }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center min-h-screen bg-slate-200">
        <Todolist 
          data={data} 
          handleSubmit={handleSubmit}
          handleChange={handleChange}
          newTask={newTask}
          />
      </div>
      
    </>
  )
}

// const Home = () => {
//     const [item, setItem] = useState('');
//     const [tasks, setTasks] = useState([]);

    // useEffect(() => {
    //     fetch(listallitems)
    //     .then(res => res.json())

    //     .then(json => {
    //         const tasks = json.map(item => item.Task)
    //         setTasks(tasks);
    //     })
    //     console.log(json)
    // }, []);

//     const handleSubmit = (e) => {
//         e.preventDefault();

//         fetch(listallitems, {
//             method: 'POST',
//             headers: {
//               'Access-Control-Allow-Origin': '*',
//               'Access-Control-Allow-Credentials': true,
//               'Accept': 'application/json',
//               'Content-Type': 'application/json'
//             },
//             body: JSON.stringify({task: item})
//         });

//         setTasks([...tasks, item]);
//         setItem('');
//         e.target.reset();
//     };

//     const handleChange = (e) => {
//         setItem(e.target.value);
//     };

//     const todos = tasks.map((value, index) => <li key={ index }>{ value }</li>);

//     return (
//         <div>
//             <form onSubmit={ handleSubmit } >
//                 <label>Task</label>
//                 <input type="text" onChange={ handleChange } value={ item } />
//                 <button>Enter a todo</button>
//             </form>
//             <ul>{ todos }</ul>
//         </div>
//     );
// };

// export default Home;